### ISSUE TITLE
Slurm accounting service needs to be restarted

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#188] opened 2015-11-14 01:16 UTC
The accounting service appears to start too early and stops because it does not detect the cluster properly.

When restarted manually later, it works normally.

**Comment by verdurin** [comment] 2016-01-26 16:06
Just saw this again, when restarting the frontend node in a cluster:

```
[2016-01-26T15:29:03.231] error: mysql_real_connect failed: 2002 Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[2016-01-26T15:29:03.347] fatal: The database must be up when starting the MYSQL plugin.
[2016-01-26T15:35:45.639] slurmdbd version 2.6.5 started
```

This is on an Ubuntu cluster, but I notice it's using an old-style initscript, rather than Upstart.

**Comment by ewiger** [comment] 2016-03-01 15:55
Same here: this is still open in the master.

```
TASK: [Ensure SLURMdbd is running] ******************************************** 
changed: [frontend001]

TASK: [Create cluster in accounting database] ********************************* 
failed: [frontend001] => {"changed": true, "cmd": "sacctmgr list cluster -p -n | grep ^gc3cluster || sacctmgr -i -Q add cluster gc3cluster", "delta": "0:00:00.003688", "end": "2016-03-01 15:46:14.958076", "rc": 1, "start": "2016-03-01 15:46:14.954388", "warnings": []}
stderr: sacctmgr: s_p_parse_file: unable to status file "/etc/slurm-llnl/slurm.conf"
sacctmgr: fatal: something wrong with opening/reading conf file
sacctmgr: s_p_parse_file: unable to status file "/etc/slurm-llnl/slurm.conf"
sacctmgr: fatal: something wrong with opening/reading conf file

FATAL: all hosts have already failed -- aborting
2016-03-01 16:46:14 yy-uzh gc3.elasticluster[14285] ERROR Host `frontend001` had 1 failures: please re-run elasticluster setup or check the Ansible playbook `/home/yy/anaconda/share/elasticluster/providers/ansible-playbooks/site.yml`
2016-03-01 16:46:14 yy-uzh gc3.elasticluster[14285] WARNING Cluster `tmapstest` not yet configured. Please, re-run `elasticluster setup tmapstest` and/or check your configuration

WARNING: YOUR CLUSTER IS NOT READY YET!

Cluster name:     tmapstest
Cluster template: sciencecloud-slurm-devtmaps
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 2

To login on the frontend node, run the command:

    elasticluster ssh tmapstest

To upload or download files to the cluster, use the command:

    elasticluster sftp tmapstest

```

**Comment by ewiger** [comment] 2016-03-04 13:57
Cannot reproduce anymore on the latest master (https://github.com/gc3-uzh-ch/elasticluster/commit/295c617d0a12b327af776336ac70747a005330a7). Seems to be fixed.

@riccardomurri please close the issue

**Closed** 2016-09-20 15:40 UTC
Labels: slurm
