### ISSUE TITLE
qsub not found on frontend?

### ISSUE THREAD

**Issue by wlongabaugh** [gc3-uzh-ch/elasticluster#397] opened 2017-02-15 01:29 UTC
Total newbie to elasticluster, but I've been running through the "Create a Grid Engine cluster on Compute Engine" tutorial on Google Genomics, and have done a fresh pull from master. I would expect GridEngine commands, e.g. qsub, to be available on the frontend, but am not finding them. I'm not seeing any gridengine packages installed either. Am I messing up, or is there an issue here?

bill@gridengine-frontend001:\~\$ ./test.sh
Wed Feb 15 01:22:50 UTC 2017
bill@gridengine-frontend001:\~\$ qsub test.sh
-bash: qsub: command not found
bill@gridengine-frontend001:\~\$

**Comment by riccardomurri** [comment] 2017-02-15 09:41
hi @wlongabaugh 

>  I would expect GridEngine commands, e.g. qsub, to be available on the frontend

This is exactly what should happen.  I cannot however reproduce the issue with my test configuration.  Can you please share the ElastiCluster configuration that you are using?  (Please watch out and remove/hide all sensitive information, especially passwords)

**Comment by wlongabaugh** [comment] 2017-02-15 17:27
\# Gridengine software to be configured by Ansible
[setup/ansible-gridengine]
provider=ansible
frontend_groups=gridengine_master
compute_groups=gridengine_worker

\# Create a cloud provider (call it "google-cloud")
[cloud/google-cloud]
provider=google
gce_project_id=XXX
gce_client_id=YYY
gce_client_secret=ZZZ

\# Create a login (call it "google-login")
[login/google-login]
image_user=MYNAME
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=\~/.ssh/google_compute_engine
user_key_public=\~/.ssh/google_compute_engine.pub

\# Bring all of the elements together to define a cluster called "gridengine"
[cluster/gridengine]
cloud=google-cloud
login=google-login
setup=ansible-gridengine
security_group=default
image_id=debian-8-jessie-v20170124
flavor=n1-standard-1
frontend_nodes=1
compute_nodes=3
image_userdata=
ssh_to=frontend

**Comment by wlongabaugh** [comment] 2017-02-15 19:01
The config file is a copy & paste of the example on the tutorial, though I changed two entries that the startup warned about when parsing the config file: 1) compute_groups=gridengine_worker (was gridengine_clients) and 2) setup=ansible-gridengine (was setup-provider). I'm seeing now that the second change is probably what messed things up? I will go check that.

**Comment by riccardomurri** [comment] 2017-02-15 19:52
The config file looks correct as-is. We must look in another direction...


Can you please post the entire screen output of running 'elasticluster
setup gridengine' ? (It'll be rather long.)

**Comment by wlongabaugh** [comment] 2017-02-15 20:55
Here is the -vvv output. It is true that on start the system fails to connect via SSH, though I just took that as an advisory message, since it says at the end that the "cluster is ready". I figured the SSH problem was due to a firewall issue. I can get in fine using gcloud ssh. 

Maybe this discussion is better moved over to the mailing list? I submitted a bug because I saw some other past bugs about qsub missing, and saw some recent github commits related to the ansible-gridengine package. But I know this is not the place for user support issues. 

<pre><code>
2017-02-15 12:43:35 Yam.local gc3.elasticluster[37050] DEBUG Checking section `cluster/gridengine` ...
2017-02-15 12:43:35 Yam.local gc3.elasticluster[37050] DEBUG Checking section `login/google-login` ...
2017-02-15 12:43:35 Yam.local gc3.elasticluster[37050] DEBUG Checking section `setup/ansible-gridengine` ...
2017-02-15 12:43:35 Yam.local gc3.elasticluster[37050] DEBUG Checking section `cloud/google-cloud` ...
2017-02-15 12:43:35 Yam.local gc3.elasticluster[37050] DEBUG Using class <class 'elasticluster.providers.ansible_provider.AnsibleSetupProvider'> from module <module 'elasticluster.providers.ansible_provider' from '/Users/bill/Cluster/elasticluster/src/elasticluster/providers/ansible_provider.pyc'> to instanciate provider 'ansible'
2017-02-15 12:43:35 Yam.local gc3.elasticluster[37050] DEBUG Using class <class 'elasticluster.providers.gce.GoogleCloudProvider'> from module <module 'elasticluster.providers.gce' from '/Users/bill/Cluster/elasticluster/src/elasticluster/providers/gce.pyc'> to instanciate provider 'google'
2017-02-15 12:43:35 Yam.local gc3.elasticluster[37050] DEBUG Trying to connect to host frontend001 (104.198.191.138)
2017-02-15 12:43:36 Yam.local gc3.elasticluster[37050] DEBUG Ignoring error not a valid EC private key file connecting to frontend001
2017-02-15 12:43:36 Yam.local gc3.elasticluster[37050] DEBUG Trying to connect to host compute001 (104.154.247.164)
2017-02-15 12:43:36 Yam.local gc3.elasticluster[37050] DEBUG Ignoring error not a valid EC private key file connecting to compute001
2017-02-15 12:43:36 Yam.local gc3.elasticluster[37050] DEBUG Trying to connect to host compute002 (104.154.55.25)
2017-02-15 12:43:37 Yam.local gc3.elasticluster[37050] DEBUG Ignoring error not a valid EC private key file connecting to compute002
2017-02-15 12:43:37 Yam.local gc3.elasticluster[37050] DEBUG Trying to connect to host compute003 (104.198.75.201)
2017-02-15 12:43:37 Yam.local gc3.elasticluster[37050] DEBUG Ignoring error not a valid EC private key file connecting to compute003
2017-02-15 12:43:37 Yam.local gc3.elasticluster[37050] INFO No inventory file was created.
2017-02-15 12:43:37 Yam.local gc3.elasticluster[37050] INFO No setup required for this cluster.
Updating cluster `gridengine`...
Configuring cluster `gridengine`...
Your cluster is ready!

Cluster name:     gridengine
Cluster template: gridengine
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 3

To login on the frontend node, run the command:

    elasticluster ssh gridengine

To upload or download files to the cluster, use the command:

    elasticluster sftp gridengine
<code><pre>

**Comment by riccardomurri** [comment] 2017-02-15 21:17
This looks like the culprit:

>        2017-02-15 12:43:37 Yam.local gc3.elasticluster[37050] INFO No setup required for this cluster.

So ElastiCluster thinks there is nothing to set up, and did not run Ansible *at all*.  That's why you don't have `qsub` on your frontend: nothing has been installed, it's just a plain Debian 8 VM.  So there's certainly a bug here: that ElastiCluster deems a cluster OK when in fact it could not connect to *any* of its nodes.

Now the question is: why couldn't it connect?  The log says:

> Ignoring error not a valid EC private key file connecting to frontend001

This looks to me another instance of https://github.com/gc3-uzh-ch/elasticluster/issues/359 -- can you please have a look at 
https://github.com/gc3-uzh-ch/elasticluster/issues/359#issuecomment-264281444 and tell if the workaround suggested there solves the problem? (Basically, you should either use `ssh-agent` or rename your SSH key files to `~/.ssh/id_ecdsa` and `~/.ssh/id_ecdsa.pub`)

**Comment by wlongabaugh** [comment] 2017-02-15 22:36
Agreed, this bug should indeed be changed to "ElastiCluster deems a cluster OK even if cannot connect to nodes". I just got it to work, and indeed qsub et al are now there. To a newbie like me, it seemed the failure to connect via SSH was just an advisory message, not a show-stopper.

The problem was actually in my "image_user" entry. It turns out that over at Google Genomic readthdocs, they provide this in the template file:

<pre><code>image_user=****REPLACE WITH YOUR GOOGLE USERID (just the userid, not email)****</code></pre>

Which I (DUH) incorrectly took to mean my username (which is "Firstname Lastname") instead of the user part of the email. At least the Elasticluster docs is more explicit on this. As soon as I specified my email username, it worked. It also accepted my laptop username for that field. After that was fixed, things worked fine (I am running SSH Agent to deal with the keystore password).

Thanks.

**Comment by riccardomurri** [comment] 2017-02-16 15:48
I have opened two separate threads for the logging and the setup issues -- I do not like when people have to read a long thread to find out that the topic changed completely halfway through.

If you don't mind, I'll close this issue and continue working on solving the "root cause" in #398 and #399

**Closed by riccardomurri** 2017-02-16 15:48 UTC
Labels: gridengine
