### ISSUE TITLE
Ctrl+C interruption by user causes confusion in persistence state on cluster start  

### ISSUE THREAD

**Issue by ewiger** [gc3-uzh-ch/elasticluster#93] opened 2014-07-07 16:14 UTC
It is a low priority persistence bug but it is still nice to fix.

I follow the *quick start* instructions for the **usecase**  SLURM on OpenStack as according to documentation. To reproduce the problem:

1. Configure ~/.elasticluster/config to run  SLURM on OpenStack. Use proper openstack credentials.
2. Run elasticluster -v start slurm -n cicero
3. Wait about 5 secs. Press CTRL+C (user break)
4. Manually terminate (3) running instances in the openstack dashboard.
5. Repeat the **elasticluster** command.

Output:
```
>elasticluster -v start slurm -n cicero
Starting cluster `cicero` with 1 frontend nodes.
Starting cluster `cicero` with 2 compute nodes.
(this may take a while...)
INFO:gc3.elasticluster:Not starting node frontend001 which is already up&running.
INFO:gc3.elasticluster:Not starting node compute002 which is already up&running.
INFO:gc3.elasticluster:Not starting node compute001 which is already up&running.
INFO:gc3.elasticluster:Ignoring unknown ssh-rsa host key for 130.60.24.94: 795a6072c707d4b631169a018e7a8b83
```

Elastic thinks that instances are running but in fact they are not.

**Comment by riccardomurri** [comment] 2016-10-05 15:47
I cannot reproduce this with the latest "master" code.

Assuming it has been fixed in the many commits that happened since the bug was reported.

**Closed by riccardomurri** 2016-10-05 15:47 UTC
Labels: 2 - Working <= 5, bug
