### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by hitblz** [gc3-uzh-ch/elasticluster#395] opened 2017-02-11 01:48 UTC
I 'd like to know is it okay to make elaticluster work under python3 environment with 2to3 tool?

**Comment by riccardomurri** [comment] 2017-02-13 11:36
hello @hitblz , I have never tried comverting the ElastiCluster source with `2to3` so that would indeed be an interesting experiment to try.  Since ElastiCluster can run pretty isolated in its own virtual environment, it's not top priority for me to get it Python 3 compatible (scheduled for release 1.5, currently working on 1.3), but I am certainly willing to help if you decide to try it yourself.

**Comment by yarikoptic** [comment] 2019-03-18 23:38
we used to use `2to3` to convert pymvpa code base upon installation to support python3... but it is really inconvenient since any change in the source code needs first  to be converted before could even be tested. makes it inconvenient to debug anything.
That is why projects moved away toward supporting both 2 and 3 in the same code base using [six](https://pythonhosted.org/six/) or [python-future](http://python-future.org).  I am more familiar with `six` which is just a straightforward helper providing adapters where needed and unified import space.  So if providing support for python3 for a new project, I would use it.
`python-future` is a bit more magical.  Some one could make probably analogy that six to python-future is like `nose` to `pytest` ;)  It provides a helper tool `futurize` to assist converting code to support both 2 and 3, so it makes it easier to convert existing code bases to support both 2 and 3. Ideally every converted file should be reviewed, tested and then committed.  It is nice whenever code base is modularized so you can start literally with the very core/base and slowly expand. We started to do it for PyMVPA, but it is a slow WiP (not a priority).
So my not too well educated advice would be to try http://python-future.org to migrate to support both python2 and 3.  I do not think it would be feasible to maintain separate code bases for 2 and 3, and probably not needed since 2to3 converted code would also need to be checked/tested - not alike after `futurize`.

**Comment by riccardomurri** [comment] 2019-03-29 11:57
Work on porting ElastiCluster to Python 3 is in progress here: https://github.com/riccardomurri/elasticluster/tree/python3

Most low-hanging fruits were already reaped (use `futurize`, fix a couple of additional import/name changes) and now the test status is: 16 failed, 50 passed, 10 warnings.

I guess the hard part lies ahead: YAML requiring that node and cluster names be `bytes` objects instead of `str`, incompatibilities with `pickle` and with `boto`...  I still need to take a close look, though.

**Comment by riccardomurri** [comment] 2019-03-29 11:58
cc @ndmckinley -- you might be more experienced than me on Py2 vs Py3 issues.

**Comment by riccardomurri** [comment] 2019-03-29 16:13
All tests passing!

(Unfortunately, `futurize` made changes that are backwards-incompatible with Py2 -- all those `from builtins import ...` so the code on this branch won't run in Py2)

**Comment by yarikoptic** [comment] 2019-03-29 17:28
@riccardomurri could that branch be suggested as a PR against this repository, then we will see how python 2.7 tests fail. theoretically `futurize` iirc should make all imports work on both 2 and 3

**Comment by riccardomurri** [comment] 2019-03-29 18:09
> (Unfortunately, futurize made changes that are backwards-incompatible with Py2 -- all those from builtins import ... so the code on this branch won't run in Py2)

I would guess the issue is not in `futurize`; it's probably related to the interaction of `future.standard_library.install_aliases()` and  `pytest` -- the monkey-patching done by the former is not picked up by the latter...

**Comment by riccardomurri** [comment] 2019-03-29 18:11
@yarikoptic Py3 supporting code is now in https://github.com/gc3-uzh-ch/elasticluster/pull/623

**Comment by riccardomurri** [comment] 2019-03-29 18:15
>  would guess the issue is not in `futurize`

Indeed it's not. 

My bad: I had forgotten to reinstall package `elasticluster` in the Py2 test environment, so `future` was not there and this cascaded onto a number of other failures ...

**Comment by riccardomurri** [comment] 2019-03-29 18:23
All tests passing, on both Python 2.7.15 and 3.6.7 on my laptop.

**Comment by riccardomurri** [comment] 2019-03-29 18:33
All tests passing on Travis CI as well.

**Comment by riccardomurri** [comment] 2019-03-29 18:38
I think this is ready to merge, as soon as someone else can provide some confirmation that it works not just on my machine.

**Comment by ndmckinley** [comment] 2019-04-01 11:33
> cc @ndmckinley -- you might be more experienced than me on Py2 vs Py3 issues.

Sorry, quite late to respond, but I'm afraid it's not my area of expertise.  :(

**Comment by riccardomurri** [comment] 2019-04-01 12:55
No prob, I think it's solved now :-)  Would you have time to run a couple of tests with Py3?

**Comment by ndmckinley** [comment] 2019-04-01 13:04
Apologies - I'm between computers at the moment and haven't got a solid dev environment set up.  Probably later this week, if it's not done by then. Is that PR #623?

**Comment by riccardomurri** [comment] 2019-04-01 13:06
Absolutely no problem! Yes, it's PR #623

**Comment by riccardomurri** [comment] 2019-04-04 19:55
PR #623 has been merged into "master" -- ElastiCluster now officially can run on Python3!

**Closed by riccardomurri** 2019-04-04 19:55 UTC
