### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by dwaggott** [gc3-uzh-ch/elasticluster#142] opened 2015-01-13 21:45 UTC
Any plans?

**Comment by nicolasbaer** [comment] 2015-01-25 20:59
I don't have any experience with azure and unfortunately no account either. However, if someone is interested in integrating Azure. This would be the interface to implement: https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/providers/__init__.py

**Comment by dsteinkraus** [comment] 2015-02-01 17:48
I am actively considering jumping in on this.

**Comment by bobd00** [comment] 2015-02-02 04:47
Nicolas,
I am new to github but I would like to see elasticluster support Linux VMs on Azure too.  Would it better to fork the project and them submit pull requests or how would you like to see contributions to the elasticluster project?
I took a quick look and some of the dependent code appears to rely on Linux packages/code(ansible\constants.py, fcntl.py, termios & tty).  That should work from Linux hosts kicking off the cluster, but we'll need some alternate paths to support Windows clients managing with elasticluster too.

**Comment by nicolasbaer** [comment] 2015-02-03 19:40
Great to here that you are interested in contributing. Yes, the proper way to contribute is to fork the project and create a pull request to merge the changes back. I'm currently setting up integration tests for amazon and google compute engine using [vcrpy](https://github.com/kevin1024/vcrpy) . We could then do the same for azure, so we can maintain the code at least partially without an azure account.

We use ansible to deploy and configure software on top of the vanilla images. As far as i know ansible only works on linux and mac. However, there seem to be blogposts about how to run it on cygwin or what works in any case is a virtual machine. We started working on a web application that supports the basic operations of elasticluster. So you could setup one linux machine to run the web server and windows clients could control their clusters through the web interface. Development of the web interface stopped a while ago, but I might have some time next month to get a first version done supporting the most basic features, if people are interested.

**Comment by cocoy** [comment] 2015-02-04 09:26
With Ansible 1.7, it supports windows using powershell remoting.
This link might help http://docs.ansible.com/intro_windows.html

**Comment by bobd00** [comment] 2015-02-07 00:57
Thanks I'll have to look at vcrpy.
I took at look at the ansible web site and it looked like ansible had to be on a *nix host but could have playbooks that target windows.  At the moment we want to target clusters of *nix VMs and will not be running Windows VMs on Azure, so we can focus on the *nix / Azure work for now.  
hoping to get some time to start soon .

**Comment by YidingZhou** [comment] 2015-03-03 18:48
interesting. how's this going?

**Comment by dsteinkraus** [comment] 2015-03-03 21:06
It's coming along. I can create a cluster and wait for all the nodes to be started. I haven't gotten to the provisioning stage yet.

**Comment by dsteinkraus** [comment] 2015-06-17 23:46
The Azure cloud provider is working quite well, and I am about ready to create some pull requests. But I have a question about how the cloud provider is meant to store its own state.

To get good performance starting and stopping large clusters in Azure, you need to create multiple resources (cloud services and storage accounts, primarily). My provider does this, and when stopping a cluster, it needs to know what resources it created. Prior to the last batch of elasticluster changes, when the stop command was issued, the Azure cloud provider state was unpickled along with the rest of the cluster, so this information was available for teardown.

I was never sure this was by design - after all, cluster.py does delete the cloud provider and setup provider from its state when unpickled (cluster.py line 213). But for some reason, the provider state was there anyway when my stop_instance got called. But with the latest elasticluster, the state of the cloud provider doesn't seem to come back even if storage_type = pickle is specified in the config (and of course if non-pickle storage is used, there's no question of getting back the state of the cloud provider).

So my question is: is there a "right way" in the elasticluster design for a cloud provider to store private state that it will need later? And if so, what is it? (Perhaps the preferred answer is "don't do it", but that won't really work for Azure.)

I am currently changing my provider to save state in its own pickle file in the storage directory under a cluster-specific name. I know this will work, but if some other solution is preferable, I'll change it.

**Comment by nicolasbaer** [comment] 2015-06-24 21:28
Great to hear that there is progress. I'd like to better understand what kind of properties you want to store for the cloud provider. Could you briefly elaborate on the attributes? Until now we only had to store properties for the cluster and the nodes (e.g. instance id) and there's no implementation (yet) to store cloud provider related information.

**Comment by dsteinkraus** [comment] 2015-06-24 22:04
Building a cluster on Azure is more complex than on, say, Amazon EC2. First you have to create one or more "cloud services" into which VMs can be deployed. Then you have to create one or more "storage accounts" to hold the virtual hard drives that will host the OS for each VM. Finally you create a virtual network to allow the nodes to talk to each other at a good speed; and then you can start creating actual VMs. If you are building a large cluster (over say 100 nodes), you will want to use multiple cloud services, storage accounts, and perhaps even subscriptions (which contain all of the above resources), in order to get around speed limits in starting, stopping, and using the cluster (some of which are throttling limits imposed by Azure that are known to exist but not documented).

My provider hides all that from the user (although you can manually configure things like the number of cloud services if you want to), and to do so - and to clean everything up properly at cluster teardown - it has to know what it created. And it uses the absolute index of the node as part of the node name, so that it can do math on that index to figure out which cloud service, which storage account, and which subscription it belongs to.

I implemented a solution where the AzureCloudProvider object writes the state it needs to a .pickle file in the storage directory, so the cluster doesn't need to know the state is being saved. It works fine, and if Azure is the only provider that has such complicated needs, maybe it could be looked at as an implementation detail. If others would need it too, that would argue for a more general solution. But one of my goals has been to require as few changes to the elasticluster core as possible.

**Comment by riccardomurri** [comment] 2017-08-09 12:29
Azure support added in commit https://github.com/gc3-uzh-ch/elasticluster/commit/00096f79166695f7e4e793ceb5e7eaa410e8ac87 so I'm closing this issue.

Many, many thanks to @dsteinkraus for contributing the code and keeping it until merged!

**Closed by riccardomurri** 2017-08-09 12:29 UTC
