### ISSUE TITLE
hadoop+spark playbook fails: AnsibleUndefinedVariable

### ISSUE THREAD

**Issue by jimypbr** [gc3-uzh-ch/elasticluster#295] opened 2016-07-18 14:04 UTC
I am trying to start the Hadoop+Spark playbook described in the elasticluster manual on a private OpenStack instance.

The config I am using for the hadoop+spark playbook is:
```
[cluster/hadoop+spark]
cloud=vss
login=ubuntu
security_group=default
#Ubuntu 14.04 LTS
image_id=12a6e828-251d-448a-b88e-903a70068fa5
flavor=m1.small
master_nodes=1
worker_nodes=4
ssh_to=master
setup_provider=hadoop+spark

[setup/hadoop+spark]
provider=ansible
master_groups=hadoop_master
worker_groups=hadoop_worker
```

I am using `ANSIBLE_SSH_PIPELINING=1`.

After running `elasticluster -vvv start hadoop+spark` the setup eventually fails with the error:
```
TASK [postgresql : PostgreSQL | Update configuration - pt. 1 (pg_hba.conf)] ****
task path: /home/jb914/elasticluster/elasticluster/share/playbooks/roles/postgresql/tasks/configure.yml:72
fatal: [master001]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: {{HIVE_CLIENTS|default([HIVE_METASTORE_HOST])}}: {{groups.hive_server[0]}}: 'dict object' has no attribute 'hive_server'"}
```

**Comment by riccardomurri** [comment] 2016-07-19 15:29
I cannot reproduce this using latest "master" branch (commit a2c315c -- but none of the recent commits affected Hadoop/Spark) and our local OpenStack cloud.

What version of ElastiCluster are you using?

**Comment by jimypbr** [comment] 2016-07-19 15:46
I have gotten the same error message with the latest commit on the master branch (68ee05e). Thanks.

**Comment by riccardomurri** [comment] 2016-07-19 20:05
What version of Ansible are you running?

**Comment by jimypbr** [comment] 2016-07-20 11:14
I have version 2.1.0.0 of ansible, Python 2.7.5, and I also have these things installed in a virtualenv.

**Comment by jimypbr** [comment] 2016-07-20 11:38
I just tried it outside of a virtualenv and it still failed with the same error.

**Comment by riccardomurri** [comment] 2016-07-20 12:49
I can reproduce the error with Ansible 2.1.  It might be another instance of the problem referenced in #287 and #290 

Anyway, for a quick workaround, you can just downgrade Ansible to 2.0.x

**Comment by riccardomurri** [comment] 2016-07-20 14:17
This should be fixed in commit https://github.com/gc3-uzh-ch/elasticluster/commit/8439e06c7ebec09e02cfc9f7242c9c739ea32f6a (latest "master") -- can you please check that it works for you as well?

**Comment by jimypbr** [comment] 2016-07-20 14:51
I can confirm that both the workaround and your bugfix in 8439e06 fixed the problem for me. Thank you!

**Comment by riccardomurri** [comment] 2016-07-20 15:10
Thanks, I'm marking this issue as solved then.

**Closed by riccardomurri** 2016-07-20 15:10 UTC
Labels: bug, fix available
