### ISSUE TITLE
pvfs2 ssh file incorrectly specified

### ISSUE THREAD

**Issue by GlastonburyC** [gc3-uzh-ch/elasticluster#293] opened 2016-07-06 22:22 UTC
Setting up an elasticluster with pvfs2 fails due to the directory being incorrect:

```
TASK [Setup SSH known hosts file] **********************************************
fatal: [compute002]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/roles/common/templates/etc/ssh/ssh_known_hosts.j2'"}
fatal: [compute001]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/roles/common/templates/etc/ssh/ssh_known_hosts.j2'"}
fatal: [compute003]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/roles/common/templates/etc/ssh/ssh_known_hosts.j2'"}
fatal: [compute004]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/roles/common/templates/etc/ssh/ssh_known_hosts.j2'"}
fatal: [compute005]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/roles/common/templates/etc/ssh/ssh_known_hosts.j2'"}
fatal: [frontend001]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/roles/common/templates/etc/ssh/ssh_known_hosts.j2'"}
```

It should be:
`/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/common/templates/etc/ssh/ssh_known_hosts.j2'
`

The /roles/ folder is accidentally duplicated in the file path.

**Comment by riccardomurri** [comment] 2016-07-07 08:50
The natural fix, i.e. changing the path `src=roles/common/...` with `src=common/...` unfortunately breaks the "common" roles, due to a difference in the way handles includes when done from a playbook vs when done from a role...

Since I am going to rework most top-level playbooks to make use of roles anyway, the only fix I can suggest at the moment is to make a symlink::

    ln -sv . /home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/roles

Can you please try and tell me if it fixes the issue for you?

**Comment by GlastonburyC** [comment] 2016-07-07 09:57
It gets further with the symbolic link:
```

[](TASK [get_url] *****************************************************************
fatal: [compute003]: FAILED! => {"changed": false, "dest": "/root/", "failed": true, "gid": 0, "group": "root", "mode": "0700", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "http://orangefs.org/downloads/LATEST/source/orangefs-2.8.7.tar.gz"})


But the orangeFS link is wrong.
```

**Comment by riccardomurri** [comment] 2016-07-07 11:15
Issues with PVFS2/OrangeFS should all be fixed in the latest "master" (commit 68ee05e or later) -- at least, I am able to successfully create an OrangeFS cluster on Ubuntu 14.04.

Can you please check?

**Comment by GlastonburyC** [comment] 2016-07-07 12:49
Progress to the following error:

```
TASK [command] *****************************************************************
fatal: [compute001]: FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname == groups.pvfs2_meta[0]' failed. The error was: error while evaluating conditional (inventory_hostname == groups.pvfs2_meta[0]): 'dict object' has no attribute 'pvfs2_meta'\n\nThe error appears to have been in '/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/pvfs2.yml': line 35, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - action: shell pvfs2-genconfig --quiet --protocol tcp --ioservers {{groups.pvfs2_data|join(',')}} --metaservers {{groups.pvfs2_meta|join(',')}}  --storage /srv/pvfs2 /etc/pvfs2-fs.conf creates=/etc/pvfs2-fs.conf\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
fatal: [compute004]: FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname == groups.pvfs2_meta[0]' failed. The error was: error while evaluating conditional (inventory_hostname == groups.pvfs2_meta[0]): 'dict object' has no attribute 'pvfs2_meta'\n\nThe error appears to have been in '/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/pvfs2.yml': line 35, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - action: shell pvfs2-genconfig --quiet --protocol tcp --ioservers {{groups.pvfs2_data|join(',')}} --metaservers {{groups.pvfs2_meta|join(',')}}  --storage /srv/pvfs2 /etc/pvfs2-fs.conf creates=/etc/pvfs2-fs.conf\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
fatal: [compute005]: FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname == groups.pvfs2_meta[0]' failed. The error was: error while evaluating conditional (inventory_hostname == groups.pvfs2_meta[0]): 'dict object' has no attribute 'pvfs2_meta'\n\nThe error appears to have been in '/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/pvfs2.yml': line 35, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - action: shell pvfs2-genconfig --quiet --protocol tcp --ioservers {{groups.pvfs2_data|join(',')}} --metaservers {{groups.pvfs2_meta|join(',')}}  --storage /srv/pvfs2 /etc/pvfs2-fs.conf creates=/etc/pvfs2-fs.conf\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
fatal: [compute002]: FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname == groups.pvfs2_meta[0]' failed. The error was: error while evaluating conditional (inventory_hostname == groups.pvfs2_meta[0]): 'dict object' has no attribute 'pvfs2_meta'\n\nThe error appears to have been in '/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/pvfs2.yml': line 35, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - action: shell pvfs2-genconfig --quiet --protocol tcp --ioservers {{groups.pvfs2_data|join(',')}} --metaservers {{groups.pvfs2_meta|join(',')}}  --storage /srv/pvfs2 /etc/pvfs2-fs.conf creates=/etc/pvfs2-fs.conf\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
fatal: [compute003]: FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname == groups.pvfs2_meta[0]' failed. The error was: error while evaluating conditional (inventory_hostname == groups.pvfs2_meta[0]): 'dict object' has no attribute 'pvfs2_meta'\n\nThe error appears to have been in '/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/pvfs2.yml': line 35, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - action: shell pvfs2-genconfig --quiet --protocol tcp --ioservers {{groups.pvfs2_data|join(',')}} --metaservers {{groups.pvfs2_meta|join(',')}}  --storage /srv/pvfs2 /etc/pvfs2-fs.conf creates=/etc/pvfs2-fs.conf\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
fatal: [frontend001]: FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname == groups.pvfs2_meta[0]' failed. The error was: error while evaluating conditional (inventory_hostname == groups.pvfs2_meta[0]): 'dict object' has no attribute 'pvfs2_meta'\n\nThe error appears to have been in '/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/roles/pvfs2.yml': line 35, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - action: shell pvfs2-genconfig --quiet --protocol tcp --ioservers {{groups.pvfs2_data|join(',')}} --metaservers {{groups.pvfs2_meta|join(',')}}  --storage /srv/pvfs2 /etc/pvfs2-fs.conf creates=/etc/pvfs2-fs.conf\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

**Comment by riccardomurri** [comment] 2016-07-07 15:07
> 'dict object' has no attribute 'pvfs2_meta'

Did you give any host groups the "pvfs2_meta" class?

I have this in my config::

    [setup/pvfs2]
    provider=ansible

    master_groups=pvfs2_meta,pvfs2_client
    worker_groups=pvfs2_data,pvfs2_client

    [cluster/ubuntu]
    master_nodes=1
    worker_nodes=2
    ssh_to=master

    setup_provider=pvfs2

    # ...

**Comment by GlastonburyC** [comment] 2016-07-07 15:10
```
I have the following:


[cluster/slurm+pvfs2]
cloud=openstack
network_ids=7d326b6a-fae5-4c4f-87e4-e7b5a3628fc1
login=ubuntu
security_group=icmp-ssh-rna-seq-map-ref
image_id=1b1e4418-b710-4fd0-b143-517ac23d22a9
flavor=CraigGlusterFS
frontend_nodes=1
compute_nodes=5
pvfs2-nodes=10
setup_provider=ansible_slurm+pvfs2
ssh_to=frontend

```

```
[setup/ansible_slurm+pvfs2]
provider=ansible
frontend_groups=slurm_master,pvfs2_client
compute_groups=slurm_workers,pvfs2_client
ansible_ssh_pipelining=no
pvfs-nodes_groups=pvfs2_meta,pvfs2_data
```

**Comment by riccardomurri** [comment] 2016-07-07 15:25
There are typos in `pvfs2-nodes` in the `[cluster/...]` section, and
`pvfs-nodes_groups=...` in the `[setup/...]` section:

1. a node kind definition *must* end with `_nodes`: underscore instead of dash;
2. in the second, when you remove the `_groups` trailing part, you must end up with a node kind name: in this case it would be either `pvfs2` or `pvfs2-nodes` depending on how you fix 1.

Can you please try the following config? (fill the `# ...` with what you have now)

    [cluster/slurm+pvfs2]
    # ...
    frontend_nodes=1
    compute_nodes=5
    pvfs2_nodes=10

    [setup/ansible_slurm+pvfs2]
    # ...
    pvfs2_groups=pvfs2_meta,pvfs2_data

**Comment by GlastonburyC** [comment] 2016-07-07 15:30
That means the following documentation is wrong?

[](http://elasticluster.readthedocs.io/en/latest/playbooks.html#orangefs-pvfs2)

**Comment by riccardomurri** [comment] 2016-07-07 15:34
Yes, sorry -- just fixed it.

**Comment by GlastonburyC** [comment] 2016-07-07 15:39
That leads to a bigger problem:
Config:

```
[cluster/slurm+pvfs2]
cloud=openstack
network_ids=7d326b6a-fae5-4c4f-87e4-e7b5a3628fc1
login=ubuntu
security_group=icmp-ssh-rna-seq-map-ref
image_id=1b1e4418-b710-4fd0-b143-517ac23d22a9
flavor=CraigGlusterFS
frontend_nodes=1
compute_nodes=5
pvfs2_nodes=10
setup_provider=ansible_slurm+pvfs2
ssh_to=frontend
```
```
[setup/ansible_slurm+pvfs2]
provider=ansible
frontend_groups=slurm_master,pvfs2_client
compute_groups=slurm_workers,pvfs2_client
ansible_ssh_pipelining=no
pvfs2_groups=pvfs2_meta,pvfs2_data
```

```
Traceback (most recent call last):
  File "/usr/bin/elasticluster", line 9, in <module>
    load_entry_point('elasticluster==1.3.dev0', 'console_scripts', 'elasticluster')()
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 205, in main
  File "/usr/lib/python2.7/site-packages/cli/app.py", line 245, in run
    return self.post_run(returned)
  File "/usr/lib/python2.7/site-packages/cli/app.py", line 241, in run
    returned = self.main(*args)
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 191, in main
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 86, in __call__
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 188, in execute
  File "build/bdist.linux-x86_64/egg/elasticluster/conf.py", line 233, in create_cluster
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 386, in add_nodes
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 320, in add_node
ValueError: Invalid name `pvfs2`. The `kind` argument may only contain alphanumeric characters, as it is going to be used as host name
```

**Comment by riccardomurri** [comment] 2016-07-07 15:41
Can you please  try replacing `pvfs2_nodes=10` with `orangefs_nodes=10` and `pvfs2_groups=...` with `orangefs_groups=...` ?

**Comment by GlastonburyC** [comment] 2016-07-07 18:19
Cluster build completes but with the following error:
```

TASK [mount] *******************************************************************
fatal: [frontend001]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /pvfs2: mount: Not a directory\n"}
fatal: [compute004]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /pvfs2: mount: Not a directory\n"}
fatal: [compute005]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /pvfs2: mount: Not a directory\n"}
fatal: [compute003]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /pvfs2: mount: Not a directory\n"}
fatal: [compute002]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /pvfs2: mount: Not a directory\n"}
fatal: [compute001]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /pvfs2: mount: Not a directory\n"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/site.retry

PLAY RECAP *********************************************************************
compute001                 : ok=66   changed=42   unreachable=0    failed=1   
compute002                 : ok=66   changed=42   unreachable=0    failed=1   
compute003                 : ok=66   changed=42   unreachable=0    failed=1   
compute004                 : ok=66   changed=42   unreachable=0    failed=1   
compute005                 : ok=66   changed=42   unreachable=0    failed=1   
frontend001                : ok=78   changed=52   unreachable=0    failed=1   
orangefs001                : ok=45   changed=28   unreachable=0    failed=0   
orangefs002                : ok=43   changed=26   unreachable=0    failed=0   
orangefs003                : ok=43   changed=26   unreachable=0    failed=0   
orangefs004                : ok=43   changed=26   unreachable=0    failed=0   
orangefs005                : ok=43   changed=26   unreachable=0    failed=0   
orangefs006                : ok=43   changed=26   unreachable=0    failed=0   
orangefs007                : ok=43   changed=26   unreachable=0    failed=0   
orangefs008                : ok=43   changed=26   unreachable=0    failed=0   
orangefs009                : ok=43   changed=26   unreachable=0    failed=0   
orangefs010                : ok=43   changed=26   unreachable=0    failed=0   
```

I have checked and pvfs it is not mounted on any node.

**Comment by riccardomurri** [comment] 2016-07-07 19:36
I cannot reproduce this: a SLURM+OrangeFS cluster builds fine here.

Furthermore, the playbook is rather explicit in creating the `/pvsf2`
directory and mount point::

    - hosts: pvfs2_client
      vars:
        - pvfs2_storage: /srv/pvfs2
        - is_client: '"{{inventory_hostname}}" in {{groups.pvfs2_client}}'
      tasks:
        - action: shell modprobe pvfs2
        - action: file path=/pvfs2 state=directory
        - action: shell pgrep pvfs2-client || pvfs2-client --logtype=syslog
        - action: mount name=/pvfs2 src=tcp://{{groups.pvfs2_meta[0]}}:3334/orangefs fstype=pvfs2 opts=defaults,noauto state=mounted

Maybe it's just an artifact of several attempts?  Do you still see the error if you create and setup a new cluster from scratch?

**Comment by GlastonburyC** [comment] 2016-07-07 21:35
running the setup stage was sufficient! Thanks, seems to work.

**Comment by riccardomurri** [comment] 2016-07-07 21:43
Good! Can I close the issue then?

**Closed** 2016-07-07 21:44 UTC
Labels: bug, fix available

**Comment by GlastonburyC** [comment] 2016-07-07 21:56
However, qstat doesn't seem to work?

```
ubuntu@frontend001:~$ qstat
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /usr/lib/perl/5.18.2 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/bin/qstat line 53, <DATA> line 604.
BEGIN failed--compilation aborted at /usr/bin/qstat line 53, <DATA> line 604.
```

And sbatch submits the job, but they just stay in the queue and never run:

```
ubuntu@frontend001:~$ squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
                 2      main  sub1.sh   ubuntu PD       0:00      1 (Resources)
                 3      main  sub1.sh   ubuntu PD       0:00      1 (Resources)
```

**Comment by riccardomurri** [comment] 2016-07-07 22:05
`qstat` is an SGE command -- it's not installed on SLURM clusters (the one you're hitting is a Perl implementation of a TORQUE compatibility layer for SLURM, which I have never used and am not sure continues to work with recent versions...)

The `(Resources)` output from `squeue` means that there are not enough CPUs or memory to fulfill the job's requested allocation.  Use commands `sinfo` and `scontrol show job`, `scontrol show node` to see what's really happening.  You might have to restart the `slurmd` daemons on the compute nodes.

**Comment by GlastonburyC** [comment] 2016-07-07 22:10
I know qstat is an SGE command. I have used it previously on elasticluster setups (but on CentOS) using the following config:
```
[setup/ansible-gridengine]
provider=ansible
frontend_groups=gridengine_master
compute_groups=gridengine_clients
```
All I'm doing is a dd job to test write speed. each node has 300GB of RAM and TB's of storage, so resources really aren't the problem:

```
JobId=2 Name=sub1.sh
   UserId=ubuntu(1000) GroupId=ubuntu(1000)
   Priority=6058 Account=root QOS=normal
   JobState=PENDING Reason=Resources Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 ExitCode=0:0
   RunTime=00:00:00 TimeLimit=UNLIMITED TimeMin=N/A
   SubmitTime=2016-07-07T21:41:25 EligibleTime=2016-07-07T21:41:25
   StartTime=2016-07-08T22:07:12 EndTime=Unknown
   PreemptTime=None SuspendTime=None SecsPreSuspend=0
   Partition=main AllocNode:Sid=frontend001:12780
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=(null)
   NumNodes=1-1 NumCPUs=1 CPUs/Task=1 ReqS:C:T=*:*:*
   MinCPUsNode=1 MinMemoryNode=0 MinTmpDiskNode=0
   Features=(null) Gres=(null) Reservation=(null)
   Shared=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/home/ubuntu/sub1.sh
   WorkDir=/home/ubuntu
```

**Comment by riccardomurri** [comment] 2016-07-07 22:33
> I know qstat is an SGE command.

Yes, it is *also* an SGE command.  But on SLURM clusters it comes from the TORQUE compatibility layer and has a different syntax.  You can check that other SGE commands like `qhosts` or `qconf` are missing, whereas TORQUE/PBS commands like `pbsnodes` should instead be there.

> each node has 300GB of RAM and TB's of storage, so resources really aren't the problem:

well, somehow SLURM thinks otherwise :-)  It might be that the `slurmd` daemons are down so SLURM does not see any resource as "up".  Have you tried restarting them?

    pdsh -g slurm_workers sudo service slurm-llnl restart

Anyway, these questions are probably better discussed on the [ElastiCluster mailing list][1] than in a closed issue report...

[1]: https://groups.google.com/forum/#!forum/elasticluster
