### ISSUE TITLE
GCP sshKeys metadata deprecated

### ISSUE THREAD

**Issue by lila** [gc3-uzh-ch/elasticluster#426] opened 2017-05-03 15:20 UTC
as stated in [here](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys):

> Note: Setting the sshKeys metadata value on the instance metadata instead of the project metadata is deprecated. Compute Engine will stop supporting this metadata value in March 2017. Set the ssh-keys instance metadata value to add ssh keys for users on individual instances instead.

it seems also that by default, the instances created by elasticluster block the project-wide sshkeys, perhaps it's picking up some default somewhere, but turning that off (ie, do not block project-wide ssh keys) will better support multi-user clusters. 

- karan

**Comment by riccardomurri** [comment] 2017-05-03 22:13
Looks like a duplicate of #391 ?

**Closed** 2018-02-03 13:35 UTC
Labels: gce, ssh

**Comment by riccardomurri** [comment] 2018-02-03 13:36
Allowing project-wide SSH keys can now be enabled (default) or disabled via the `allow_project_ssh_keys` option in the cluster configuration.
