### ISSUE TITLE
processor count wrong on EC2

### ISSUE THREAD

**Issue by loveshack** [gc3-uzh-ch/elasticluster#624] opened 2019-04-01 11:34 UTC
If I start an SGE instance, the compute hosts seem always to be set up with a single slot when they're multi-core.
The template uses hostvars[item].ansible_processor_count, so I assume it's an ansible problem. (I'd prefer cores rather than processors -- x86_64 hyperthreads -- but I don't know if that's possible without specifying no hyperthreads for instances, and the implementation attempt is at least reasonable.)

**Comment by riccardomurri** [comment] 2019-04-01 15:05
I've just pushed modifications to the templates that use `ansible_processor_vcpus` (I guess it was introduced later than I had reviewed the GE playbooks, as the Spark/Hadoop ones use it already...). But:

- the number of `slots` in file `all.q.conf` seems to be ignored anyway -- right after the cluster is built, `qconf -sq all.q` shows `slots=1`.  Maybe initialization of GE parameters is being done in the wrong order? (See: https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/share/playbooks/roles/gridengine-master/tasks/main.yml#L107 line 107 and following)

- if I later load the generated template via `qconf -Mq /opt/sge/all.q.conf` then the slot count is as intended but then users lose permission to submit and no queue is in the output of `qhosts` ... so I guess the template https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/share/playbooks/roles/gridengine-master/templates/all.q.conf.j2 is wrong which might explain why it was not loaded at all in the first place.

I'm not able to spot the error right now, I need to refresh my knowledge of how to configure GE first.  But if you can see anything that is obviously incorrect please let me know.

**Comment by riccardomurri** [comment] 2019-04-01 21:38
Should be fixed in the latest "master" (according to my limited testing), please let me know if not.

**Closed** 2019-04-01 21:37 UTC
