### ISSUE TITLE
Duplicate hostnames for multiple frontend nodes

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#358] opened 2016-12-01 08:01 UTC
I created a CentOS 7.2 SLURM cluster with 2 frontend nodes, because the user wanted to use 1 of them solely for incoming data transfers.

They both have the hostname of the second one:
```
[centos@pilot6-admin ~(pilot6)]$ ssh 10.2.217.130
Last login: Thu Nov 24 14:18:52 2016 from 10.2.217.25
[centos@frontend002 ~]$ hostname
frontend002
[centos@frontend002 ~]$ logout
Connection to 10.2.217.130 closed.
[centos@pilot6-admin ~(pilot6)]$ ssh 10.2.217.128
Last login: Thu Nov 24 14:22:44 2016 from 10.2.217.25
[centos@frontend002 ~]$ hostname
frontend002
```

**Comment by riccardomurri** [comment] 2016-12-01 08:21
Can you please post the relevant configuration snippet?

**Comment by verdurin** [comment] 2016-12-01 08:24
Here you go:
```
[cluster/slurm-tracerx]
cloud=emedlab
login=centos
setup_provider=ansible-slurm
security_group=<security group>
# CentOS image
image_id=<image ID>
flavor=m2.large
frontend_nodes=2
compute_nodes=34
ssh_to=frontend
network_ids=<network ID>
image_userdata=~/src/slurm-elastic-test-cloud-init.yaml
```

**Comment by riccardomurri** [comment] 2016-12-01 15:43
I cannot reproduce this issue (tried with both CentOS7 and Ubuntu 16.04 VMs);
the host names are correctly set::

    [centos@master001 ~]$ pdsh -a hostname
    worker002: worker002
    master002: master002
    worker001: worker001
    master001: master001

    [centos@master001 ~]$ pdsh -a 'getent hosts $(hostname)'
    master002: fe80::f816:3eff:fe90:ef5b master002
    worker002: fe80::f816:3eff:fefe:19e0 worker002
    worker001: fe80::f816:3eff:fe72:b508 worker001
    master001: fe80::f816:3eff:fef7:a7e8 master001

What happens, though, is that the setup of a cluster with 2 front-ends always
*fails* since both front-end nodes run the "SLURM master" playbook, only one
will have the correct `slurm.conf`; the second master node will have a
`slurm.conf` that points to `master001` as the SLURM master so the `slurmctld`
refuses to start...

If you want multiple "non-exec" nodes, may I suggest that you use the
"submit_nodes" role instead?

    [cluster/slurm-tracerx]
    # ...
    frontend_nodes=1
    compute_nodes=34
    submit_nodes=1
    # ...
    
    [setup/slurm]
    # ...
    submit_groups=slurm_submit

**Comment by verdurin** [comment] 2016-12-01 16:26
Yes, I think you're right - there was a failure with the second frontend node, which probably explains this. The rest of the cluster is working, though.

In any case, the reminder about submit nodes is a good one.

Do you want me to leave this open? I'm happy to close if not.

**Comment by riccardomurri** [comment] 2016-12-01 16:42
I'm closing this then, as there seems to be no actual bug to fix or action to be taken.

Feel free to re-open if there is more info!

**Closed by riccardomurri** 2016-12-01 16:42 UTC
