### ISSUE TITLE
TASK [slurm-master : Replace systemd unit file for SLURM services] FAILS

### ISSUE THREAD

**Issue by oweidner** [gc3-uzh-ch/elasticluster#312] opened 2016-10-03 19:38 UTC
I am trying to bootstrap a SLURM cluster in AWS with the latest master branch of elasticluster (`1.2.0-567-g22f2499`) and the following configuration: 

```
[cloud/amazon-eu-west-1]
provider=ec2_boto
ec2_url=https://ec2.eu-west-1.amazonaws.com
ec2_access_key=XXX
ec2_secret_key=XXX
ec2_region=eu-west-1
request_floating_ip=True

[login/ubuntu]
image_user=ubuntu
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/elasticluster
user_key_public= ~/.ssh/elasticluster.pub


[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_workers


[cluster/slurm]
cloud=amazon-eu-west-1
login=ubuntu
setup_provider=ansible-slurm
security_group=default

image_id=ami-2e4c375d
flavor=m1.small
frontend_nodes=1
compute_nodes=2
ssh_to=frontend
```

Everything works fine until this point:

```
TASK [slurm-master : Replace systemd unit file for SLURM services] *************
fatal: [frontend001]: FAILED! => {"failed": true, "msg": "the file_name '/Users/ole/development/elasticluster/src/elasticluster/share/playbooks/roles/usr/lib/systemd/system/slurm-llnl-slurmdbd.service' does not exist, or is not readable"}
```

and subsequently

```
2016-10-03 21:27:28 teahupoo.internal gc3.elasticluster[10247] ERROR Command `ansible-playbook /Users/ole/development/elasticluster/src/elasticluster/share/playbooks/site.yml --inventory=/Users/ole/.elasticluster/storage/ansible-inventory.slurm --become --become-user=root -v` failed with exit code 1.
2016-10-03 21:27:28 teahupoo.internal gc3.elasticluster[10247] ERROR Check the output lines above for additional information on this error.
2016-10-03 21:27:28 teahupoo.internal gc3.elasticluster[10247] ERROR The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup` or fix the playbooks.
2016-10-03 21:27:28 teahupoo.internal gc3.elasticluster[10247] WARNING Cluster `slurm` not yet configured. Please, re-run `elasticluster setup slurm` and/or check your configuration
```

The result is that I can ssh into the frontend, but SLURM doesn't seem to be configured correctly:

```
ubuntu@frontend001:~$ squeue 
slurm_load_jobs error: Unable to contact slurm controller (connect failure)
```

Any ideas what might have gone wrong here?

**Comment by riccardomurri** [comment] 2016-10-04 07:51
> Everything works fine until this point:
> 
> ```
> TASK [slurm-master : Replace systemd unit file for SLURM services] *************
> fatal: [frontend001]: FAILED! => {"failed": true, "msg": "the file_name '/Users/ole/development/elasticluster/src/elasticluster/share/playbooks/roles/usr/lib/systemd/system/slurm-llnl-slurmdbd.service' does not exist, or is not readable"}
> ```

All instances I have seen of this are caused by a [bug in Ansible 2.1.1.0]
Ansible 2.1.0.0 is known to work well.  I have not yet tried 2.2.0

What version of Ansible are you running together with ElastiCluster?


[1]: https://github.com/ansible/ansible/issues/16952

**Comment by oweidner** [comment] 2016-10-04 10:08
Ah, I am using 2.1.2.1 which installed as a dependency with elasticaluster. I'll try to downgrade manually and let you know.

**Comment by oweidner** [comment] 2016-10-04 11:45
Ok, so I can confirm that it works with ansible 2.1.0.0. Thanks for your help!

Would it make sense to narrow down the requirements at https://github.com/gc3-uzh-ch/elasticluster/blob/master/setup.py#L161 ?

**Comment by riccardomurri** [comment] 2016-10-04 12:43
(Ole Weidner, Tue, Oct 04, 2016 at 04:45:20AM -0700:)
> Ok, so I can confirm that it works with ansible 2.1.0.0. Thanks for
> your help!

I've also tried now Ansible 2.1.2.0 and that works too.  So it seems
that the issue is confined to Ansible 2.1.1.0


> Would it make sense to narrow down the requirements at
> https://github.com/gc3-uzh-ch/elasticluster/blob/master/setup.py#L161 ?

My understanding is that the syntax 'ansible>=2.0,!=2.1.1.0', which is
what ElastiCluster's `setup.py` has presently, is doing exactly that:
blacklisting Ansible 2.1.1.0 and allowing other versions.

Am I mistaken in this use of Python dependency specifications?

**Comment by oweidner** [comment] 2016-10-06 12:21
Hm, so the same error just came up again after I installed Elasticluster on a fresh VM. Again Ansible 2.1.2.0 installed by default with Elasticluster. 

A downgrade to 2.1.0.0 again fixed the issue, but I would consider Ansible 2.1.2.1 definitely broken - at least from an Elasticluster perspective.

Why don't you just fix the Ansible version to ansible==2.1.0.0 in setup.py instead of trying to filtering out all potentially problematic versions?

**Comment by riccardomurri** [comment] 2017-01-16 10:14
Since commit 133f10becec185c0b93257e2c8e857163e27c1b8 Ansible version >=2.2.1 is required -- does this fix all of your concerns?

**Comment by riccardomurri** [comment] 2018-01-17 15:12
ElastiCluster now requiring Ansible >= 2.3 so I'm going to close this issue as no longer relevant.

**Closed by riccardomurri** 2018-01-17 15:12 UTC
Labels: 3 - Review, ansible, fix available, slurm
