### ISSUE TITLE
Munge and SlurmDBD handler failures with Slurm

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#297] opened 2016-08-01 10:22 UTC
I'm just testing a Slurm cluster creation with the latest `master` and I see this error when configuring `Munge`:

```
TASK [slurm-common : Configure MUNGE] ******************************************
task path: /home/centos/src/venv-2016-04-25/elasticluster/src/elasticluster/share/playbooks/roles/slurm-common/tasks/munge.yml:42
ERROR! The requested handler 'restart munge' was not found in any of the known handlers
```

**Comment by verdurin** [comment] 2016-08-01 11:15
I've been able to fix this by adding a `handlers` directory to the `slurm-common` role, with the following in `main.yml`:

```
- name: restart munge
  action: service name=munge state=restarted
  when: is_centos
```

Running with this fix, I see something similar is required for `slurmdbd`...

**Comment by verdurin** [comment] 2016-08-01 14:08
Here's what I added for that case, in a new `handlers` directory for the `slurm-masters` role:

```
- name: restart slurmdbd
  action: service name=slurmdbd state=restarted
  when: is_centos
```

**Comment by riccardomurri** [comment] 2016-08-02 14:37
Should be fixed in the latest "master", can you please confirm?

**Comment by verdurin** [comment] 2016-08-03 05:58
The Munge part is fixed but the same problem is still there for SlurmDBD, as listed in the comment above.

**Comment by riccardomurri** [comment] 2016-08-03 21:24
Should really be fixed in latest master, can you please try again?

**Comment by riccardomurri** [comment] 2016-09-20 14:13
I cannot reproduce this any longer with the playbooks on the "master" branch and there have been no updates since more than a month. Therefore I'm marking the issue as solved.  Feel free to re-open if this is not the case.

**Closed by riccardomurri** 2016-09-20 14:13 UTC
Labels: 3 - Review, centos, slurm
