### ISSUE TITLE
frontend setup fails in SLURM cluster on CentOS 7

### ISSUE THREAD

**Issue by GlastonburyC** [gc3-uzh-ch/elasticluster#256] opened 2016-05-26 16:13 UTC
I get the following error message when launching a simple elasticluster ( the instances are there and I can SSH into them, but SLURM isn't working for example)

```
TASK [slurm-master : Ensure `slurmdbd` is running] *****************************
failed: [frontend001] (item=slurmdbd) => {"failed": true, "item": "slurmdbd", "msg": "Unable to start service slurmdbd: Job for slurmdbd.service failed because a configured resource limit was exceeded. See \"systemctl status slurmdbd.service\" and \"journalctl -xe\" for details.\n"}
to retry, use: --limit @/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/site.retry

PLAY RECAP *********************************************************************
compute001                 : ok=20   changed=13   unreachable=0    failed=0   
compute002                 : ok=20   changed=13   unreachable=0    failed=0   
frontend001                : ok=48   changed=33   unreachable=0    failed=1   

2016-05-26 15:52:40 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[19026] ERROR Command `ansible-playbook /home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/site.yml --inventory=/home/cglastonbury/.elasticluster/storage/ansible-inventory.slurm --sudo --sudo-user=root` failed with exit code 2.
2016-05-26 15:52:40 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[19026] ERROR Check the output lines above for additional information on this error.
2016-05-26 15:52:40 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[19026] ERROR The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup` or fix the playbooks.
2016-05-26 15:52:40 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[19026] WARNING Cluster `slurm` not yet configured. Please, re-run `elasticluster setup slurm` and/or check your configuration
WARNING: YOUR CLUSTER IS NOT READY YET!

Cluster name:     slurm
Cluster template: slurm
Default ssh to node: frontend001
- compute nodes: 2
- frontend nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh slurm

To upload or download files to the cluster, use the command:

    elasticluster sftp slurm

[cglastonbury@rna-seq-map-ref-bastion ~]$ systemctl status slurmdbd.service
Failed to get D-Bus connection: No such file or directory
```

**Comment by GlastonburyC** [comment] 2016-05-26 18:09
I've been told it's a clash between the config file and the systemd unit file. But i don't know how to fix that.

**Comment by verdurin** [comment] 2016-05-26 22:49
This is what I tried to address in #255

**Comment by riccardomurri** [comment] 2016-05-27 08:15
Can you please try again with the latest "master" branch?  I think this has been fixed in commits c3e17f59fcd0420da730d90cf687293d1633ab40 and e58390ae5fd4615454a48f98c00046d8683c9446

**Comment by GlastonburyC** [comment] 2016-05-27 09:57
I get the following error now:

`TASK [nfs-client : add to /etc/fstab] ******************************************

fatal: [compute002]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /home: mount.nfs: Connection timed out\n"}
fatal: [compute001]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /home: mount.nfs: Connection timed out\n"}
	to retry, use: --limit @/home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/site.retry

PLAY RECAP *********************************************************************
compute001                 : ok=25   changed=14   unreachable=0    failed=1   
compute002                 : ok=25   changed=14   unreachable=0    failed=1   
frontend001                : ok=57   changed=41   unreachable=0    failed=0   

2016-05-27 09:56:03 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[10341] ERROR Command `ansible-playbook /home/cglastonbury/.python-eggs/elasticluster-1.3.dev0-py2.7.egg-tmp/elasticluster/share/playbooks/site.yml --inventory=/home/cglastonbury/.elasticluster/storage/ansible-inventory.slurm --sudo --sudo-user=root` failed with exit code 2.
2016-05-27 09:56:03 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[10341] ERROR Check the output lines above for additional information on this error.
2016-05-27 09:56:03 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[10341] ERROR The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup` or fix the playbooks.
2016-05-27 09:56:03 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[10341] WARNING Cluster `slurm` not yet configured. Please, re-run `elasticluster setup slurm` and/or check your configuration`

**Comment by verdurin** [comment] 2016-05-27 09:58
@GlastonburyC - see #258 and #253

**Comment by verdurin** [comment] 2016-05-31 06:19
@GlastonburyC - I think this is working for you now?

**Comment by riccardomurri** [comment] 2016-05-31 11:08
Hello guys -- I managed to break my finger over the weekend and now I must wear a cast on the hand for one month. I'm afraid I won't be able to do much EastiCluster-related before end of June .... sorry!

**Comment by GlastonburyC** [comment] 2016-05-31 14:52
Yes, this is working. Get well soon Riccardo! :)

**Comment by riccardomurri** [comment] 2016-09-20 15:35
Related bugs have been fixed and I cannot reproduce this issue with the latest "master" playbooks.  Therefore I'm closing this as solved.  Feel free to re-open if you still run into this issue.

**Closed by riccardomurri** 2016-09-20 15:35 UTC
Labels: centos, slurm
