### ISSUE TITLE
Munge key problem?

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#181] opened 2015-08-05 20:42 UTC
I started a new Slurm cluster with Ubuntu nodes. The two compute nodes were detected, but were listed as down, because authentication was failing.

When I manually copied around the key from the frontend node and restarted munge, the two compute nodes were listed as up, in the cluster.

This is with the current development release, running on CentOS 7.1.

**Comment by riccardomurri** [comment] 2016-09-20 15:42
I cannot reproduce this with the latest "master" code; therefore I'm closing the issue as fixed.  Feel free to re-open if you still run into it.

**Closed by riccardomurri** 2016-09-20 15:42 UTC
Labels: centos, slurm
