### ISSUE TITLE
"no matching hostkey found for key ED25519" trying to SSH between Grid Engine hosts

### ISSUE THREAD

**Issue by mbookman** [gc3-uzh-ch/elasticluster#367] opened 2016-12-14 17:11 UTC
As noted in issue #357, after deploying a Grid Engine cluster on Google Compute Engine (GCE) using a Debian 8 image, I cannot SSH from one host to another (and hence Grid Engine jobs do not run).

The SSH error occurs whether trying to connect from frontend to compute or compute to frontend:

```
mbookman@frontend001:~$ ssh compute001
no matching hostkey found for key ED25519 <snip>
ssh_keysign: no reply
key_sign failed
Permission denied (publickey,hostbased).
```
and similarly:

```
mbookman@compute001:~$ ssh frontend001
no matching hostkey found for key ED25519 <snip>
ssh_keysign: no reply
key_sign failed
Permission denied (publickey,hostbased).
```

In pull request #366, @riccardomurri said:

> I guess this is a problem with ED25519 being a new and separate key type; right
> now ElastiCluster's ssh_hostbased_auth.yml only gather RSA and DSA keys for
> building the "know hosts" DB, whereas apparently the Debian 8 VMs on GCE use and
> require ED25519 by default.

**Comment by riccardomurri** [comment] 2016-12-15 15:03
Can you please upgrade to commit 592f596 and try again?  If the issue is the missing `ed25519` key, that should fix it.

**Comment by riccardomurri** [comment] 2016-12-15 15:04
Sorry I meant commit 94fda51

**Comment by mbookman** [comment] 2016-12-15 17:03
Thanks Riccardo. The SSH problem appears resolved after picking up that change.

I next found that the Grid Engine client on my worker node had failed, but I was able to restart it and submit jobs. I'll file a follow-up.

**Comment by riccardomurri** [comment] 2016-12-15 20:15
Thanks for checking! I'll close the issue then.

**Closed by riccardomurri** 2016-12-15 20:15 UTC
Labels: debian
