### ISSUE TITLE
Gluster RPMs fail to install

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#231] opened 2016-02-24 16:28 UTC
I'm testing the Gluster playbook and it fails when using a CentOS 7 instance image:

```
msg: Error: Package: glusterfs-server-3.3.1-15.el6.x86_64 (Gluster_Repo)
           Requires: glusterfs-fuse = 3.3.1-15.el6
           Available: glusterfs-fuse-3.3.1-15.el6.x86_64 (Gluster_Repo)
               glusterfs-fuse = 3.3.1-15.el6
           Installing: glusterfs-fuse-3.7.1-16.el7.x86_64 (base)
               glusterfs-fuse = 3.7.1-16.el7
Error: Package: glusterfs-server-3.3.1-15.el6.x86_64 (Gluster_Repo)
           Requires: glusterfs = 3.3.1-15.el6
           Available: glusterfs-3.3.1-15.el6.x86_64 (Gluster_Repo)
               glusterfs = 3.3.1-15.el6
           Installing: glusterfs-3.7.1-16.el7.x86_64 (base)
               glusterfs = 3.7.1-16.el7
```

**Comment by riccardomurri** [comment] 2016-05-20 23:43
Does this still happen with the latest "master"?

**Comment by riccardomurri** [comment] 2016-09-20 15:39
I cannot reproduce this with the latest "master"::

        $ pdsh -a 'rpm -qa | fgrep gluster' | dshbak -c
        ----------------
        master001,worker[001-002]
        ----------------
        glusterfs-3.7.1-16.0.1.el7.centos.x86_64
        glusterfs-client-xlators-3.7.1-16.0.1.el7.centos.x86_64
        glusterfs-fuse-3.7.1-16.0.1.el7.centos.x86_64
        glusterfs-libs-3.7.1-16.0.1.el7.centos.x86_64

I'm closing this issue as fixed; please re-open if you still run into it.

**Closed by riccardomurri** 2016-09-20 15:39 UTC
Labels: bug, centos, fix available
